const TYPES = Object.freeze({
  SELF_CONNECTED: "SELF_CONNECTED",
  CLIENT_CONNECTED: "CLIENT_CONNECTED",
  CLIENT_DISCONNECTED: "CLIENT_DISCONNECTED",
  CLIENT_MESSAGE: "CLIENT_MESSAGE",
  SERVER_MESSAGE: "SERVER_MESSAGE",
  FETCH_ALL_ROOMS: "FETCH_ALL_ROOMS",
  CREATE_ROOM: "CREATE_ROOM",
  JOIN_ROOM: "JOIN_ROOM",
  ROOM_CREATED: "ROOM_CREATED",
  ROOM_CLOSED: "ROOM_CLOSED",
  SERVER_MESSAGE: "SERVER_MESSAGE",
  FETCH_ALL_MESSAGES: "FETCH_ALL_MESSAGES_FROM_ROOM",
  SHOW_ALL_MESSAGES: "FETCH_ALL_MESSAGES_FROM_ROOM",
  PING: "PING",
});

const ROOMS = [];

module.exports = { TYPES, ROOMS };
